### ISSUE TITLE
Update buildpack to align on heroku for more recent Pip version

### ISSUE THREAD

**Issue by cyrille-sg** [Scalingo/python-buildpack#19] opened 2021-02-16 13:51 UTC
Some deps (like said here https://github.com/heroku/heroku-buildpack-python/pull/1169) are not compatible with current Pip version.

Change were made to solve this: https://devcenter.heroku.com/changelog-items/2029

**Comment by lazybird** [comment] 2021-02-22 11:03
Hello,
Thanks for you work on this buildpack.

Do you have an idea when this is issue is going to be addressed ?

This is a blocking issue, I think : some pip packages fail installing without this update.

Thanks

**Comment by EtienneM** [comment] 2021-03-01 14:48
Duplicate of #14

**Closed by EtienneM** 2021-03-01 14:48 UTC
